/*
 * SPDX-FileCopyrightText: Copyright 2020-2026 OpenRTX Contributors
 * 
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef ENGLISHSTRINGS_H
#define ENGLISHSTRINGS_H

#include "core/ui.h"
#include "ui/ui_strings.h"

const stringsTable_t englishStrings =
{
  // i18n: This should be the endonym for the language/locale; it is used in the locale selection menu
    .languageName      = gettext("English"),
    .off               = gettext("OFF"),
    .on                = gettext("ON"),
    .banks             = gettext("Banks"),
    .channels          = gettext("Channels"),
    .contacts          = gettext("Contacts"),
    .gps               = gettext("GPS"),
    .settings          = gettext("Settings"),
    .backupAndRestore  = gettext("Backup & Restore"),
    .info              = gettext("Info"),
    .about             = gettext("About"),
    .display           = gettext("Display"),
    .timeAndDate       = gettext("Time & Date"),
    .fm                = gettext("FM"),
    .m17               = gettext("M17"),
    .dmr               = gettext("DMR"),
    .defaultSettings   = gettext("Default Settings"),
    .brightness        = gettext("Brightness"),
    .contrast          = gettext("Contrast"),
    .timer             = gettext("Timer"),
    .gpsEnabled        = gettext("GPS Enabled"),
    .gpsSetTime        = gettext("GPS Set Time"),
    .UTCTimeZone       = gettext("UTC Timezone"),
    .voice             = gettext("Voice"),
    .level             = gettext("Level"),
    .phonetic          = gettext("Phonetic"),
    .beep              = gettext("Beep"),
    .backup            = gettext("Backup"),
    .restore           = gettext("Restore"),
    .batteryVoltage    = gettext("Bat. Voltage"),
    .batteryCharge     = gettext("Bat. Charge"),
    .RSSI              = gettext("RSSI"),
    .model             = gettext("Model"),
    .band              = gettext("Band"),
    .VHF               = gettext("VHF"),
    .UHF               = gettext("UHF"),
    .LCDType           = gettext("LCD Type"),
    .Niccolo           = gettext("Niccolo' IU2KIN"),
    .Silvano           = gettext("Silvano IU2KWO"),
    .Federico          = gettext("Federico IU2NUO"),
    .Fred              = gettext("Fred IU2NRO"),
    .Joseph            = gettext("Joseph VK7JS"),
    .allChannels       = gettext("All channels"),
    .menu              = gettext("Menu"),
    .gpsOff            = gettext("GPS OFF"),
    .noFix             = gettext("No Fix"),
    .fixLost           = gettext("Fix Lost"),
    .error             = gettext("ERROR"),
    .flashBackup       = gettext("Flash Backup"),
    .connectToRTXTool  = gettext("Connect to RTXTool"),
    .toBackupFlashAnd  = gettext("to backup flash and"),
    .pressPTTToStart   = gettext("press PTT to start."),
    .flashRestore      = gettext("Flash Restore"),
    .toRestoreFlashAnd = gettext("to restore flash and"),
    .openRTX           = gettext("OpenRTX"),
    .gpsSettings       = gettext("GPS Settings"),
    .m17settings       = gettext("M17 Settings"),
    .callsign          = gettext("Callsign:"),
    .resetToDefaults   = gettext("Reset to Defaults"),
    .toReset           = gettext("To reset:"),
    .pressEnterTwice   = gettext("Press Enter twice"),
    .macroMenu         = gettext("Macro Menu"),
    .forEmergencyUse   = gettext("For emergency use"),
    .pressAnyButton    = gettext("press any button."),
    .accessibility     = gettext("Accessibility"),
    .usedHeap          = gettext("Used heap"),
    .broadcast         = gettext("ALL"),
    .radioSettings     = gettext("Radio Settings"),
    .offset            = gettext("Offset"),
    .macroLatching     = gettext("Macro Latch"),
    .noGps             = gettext("No GPS"),
    .batteryIcon       = gettext("Battery Icon"),
    .CTCSSTone         = gettext("CTCSS Tone"),
    .CTCSSEn           = gettext("CTCSS En."),
    .Encode            = gettext("Encode"),
    .Decode            = gettext("Decode"),
    .Both              = gettext("Both"),
    .None              = gettext("None"),
    .direction         = gettext("Direction"),
    .step              = gettext("Step"),
    .radio             = gettext("Radio"),
    .CAN               = gettext("CAN"),
    .canRxCheck        = gettext("CAN RX Check"),
};
#endif  // ENGLISHSTRINGS_H
