name: "Build and test"
on:
  workflow_dispatch:
  push:
  pull_request:

env:
  RADIO_TOOL_VERSION: 0.2.2
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile using devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Build Linux targets
            cmake -B build_linux -DOPENRTX_TARGET=linux &&
            cmake --build build_linux &&
            cmake -B build_linux_small -DOPENRTX_TARGET=linux_smallscreen &&
            cmake --build build_linux_small &&
            cmake -B build_linux_mod17 -DOPENRTX_TARGET=linux_mod17 &&
            cmake --build build_linux_mod17 &&
            # Build ARM targets
            cmake -B build_cs7000 -DOPENRTX_TARGET=cs7000 &&
            cmake --build build_cs7000 &&
            cmake --build build_cs7000 --target openrtx_cs7000_bin &&
            cmake --build build_cs7000 --target openrtx_cs7000_dfu &&
            cmake -B build_dm1701 -DOPENRTX_TARGET=dm1701 &&
            cmake --build build_dm1701 &&
            cmake --build build_dm1701 --target openrtx_dm1701_wrap &&
            cmake -B build_dm1801 -DOPENRTX_TARGET=dm1801 &&
            cmake --build build_dm1801 &&
            cmake --build build_dm1801 --target openrtx_dm1801_wrap &&
            cmake -B build_md3x0 -DOPENRTX_TARGET=md3x0 &&
            cmake --build build_md3x0 &&
            cmake --build build_md3x0 --target openrtx_md3x0_wrap &&
            cmake -B build_md9600 -DOPENRTX_TARGET=md9600 &&
            cmake --build build_md9600 &&
            cmake --build build_md9600 --target openrtx_md9600_wrap &&
            cmake -B build_mduv3x0 -DOPENRTX_TARGET=mduv3x0 &&
            cmake --build build_mduv3x0 &&
            cmake --build build_mduv3x0 --target openrtx_mduv3x0_wrap &&
            cmake -B build_mod17 -DOPENRTX_TARGET=mod17 &&
            cmake --build build_mod17 &&
            cmake --build build_mod17 --target openrtx_mod17_bin &&
            cmake -B build_gd77 -DOPENRTX_TARGET=gd77 &&
            cmake --build build_gd77 &&
            cmake --build build_gd77 --target openrtx_gd77_wrap &&
            # Build CM7 targets
            cmake -B build_cs7000p -DOPENRTX_TARGET=cs7000p &&
            cmake --build build_cs7000p &&
            cmake --build build_cs7000p --target openrtx_cs7000p_wrap &&
            cmake --build build_cs7000p --target openrtx_cs7000p_dfu &&
            chmod -R 777 * &&
            ls build_*/ &&
            mv build_cs7000p/openrtx_cs7000p_wrap openrtx_cs7000p_${{ env.BRANCH_NAME }}.bin &&
            mv build_cs7000p/openrtx_cs7000p_dfu openrtx_cs7000p_${{ env.BRANCH_NAME }}.dfu &&
            mv build_cs7000/openrtx_cs7000_bin openrtx_cs7000_${{ env.BRANCH_NAME }}.bin &&
            mv build_cs7000/openrtx_cs7000_dfu openrtx_cs7000_${{ env.BRANCH_NAME }}.dfu &&
            mv build_dm1701/openrtx_dm1701_wrap openrtx_dm1701_${{ env.BRANCH_NAME }}.bin &&
            mv build_dm1801/openrtx_dm1801_bin.sgl openrtx_dm1801_${{ env.BRANCH_NAME }}.sgl &&
            mv build_gd77/openrtx_gd77_bin.sgl openrtx_gd77_${{ env.BRANCH_NAME }}.sgl &&
            mv build_linux/openrtx_linux openrtx_linux_${{ env.BRANCH_NAME }} &&
            mv build_md3x0/openrtx_md3x0_wrap openrtx_md3x0_${{ env.BRANCH_NAME }}.bin &&
            mv build_mduv3x0/openrtx_mduv3x0_wrap openrtx_mduv3x0_${{ env.BRANCH_NAME }}.bin &&
            mv build_mod17/openrtx_mod17_bin openrtx_mod17_${{ env.BRANCH_NAME }}.bin
      - uses: actions/upload-artifact@v4
        with:
          name: release-bins
          path: |
            ${{github.workspace}}/openrtx_cs7000p_${{ env.BRANCH_NAME }}.bin
            ${{github.workspace}}/openrtx_cs7000p_${{ env.BRANCH_NAME }}.dfu
            ${{github.workspace}}/openrtx_cs7000_${{ env.BRANCH_NAME }}.bin
            ${{github.workspace}}/openrtx_cs7000_${{ env.BRANCH_NAME }}.dfu
            ${{github.workspace}}/openrtx_dm1701_${{ env.BRANCH_NAME }}.bin
            ${{github.workspace}}/openrtx_dm1801_${{ env.BRANCH_NAME }}.sgl
            ${{github.workspace}}/openrtx_gd77_${{ env.BRANCH_NAME }}.sgl
            ${{github.workspace}}/openrtx_linux_${{ env.BRANCH_NAME }}
            ${{github.workspace}}/openrtx_md3x0_${{ env.BRANCH_NAME }}.bin
            ${{github.workspace}}/openrtx_mduv3x0_${{ env.BRANCH_NAME }}.bin
            ${{github.workspace}}/openrtx_mod17_${{ env.BRANCH_NAME }}.bin
          if-no-files-found: error
  build-zephyr:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: app
      - name: install-deps
        run: |
          sudo apt update
          sudo apt install -y git pkg-config build-essential libsdl2-dev libreadline-dev dfu-util cmake libusb-1.0-0 libusb-1.0-0-dev libcodec2-dev codec2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: xtensa-espressif_esp32s3_zephyr-elf
          sdk-version: 0.17.0
      - name: Compile zephyr
        run: |
          cd app/zephyr
          # Zephyr builds use the CMakeLists.txt.zephyr file via west
          cp CMakeLists.txt.zephyr CMakeLists.txt
          west build -b ttwrplus -d build
          python ../scripts/uf2conv.py build/zephyr/zephyr.bin -c -f ESP32S3 -b 0x0 -o openrtx_ttwrplus.uf2
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: zephyr-release-bins
          path: |
            app/zephyr/openrtx_ttwrplus.uf2
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install-deps
        run: |
          sudo apt update
          sudo apt install -y git pkg-config build-essential libsdl2-dev libreadline-dev dfu-util cmake libusb-1.0-0 libusb-1.0-0-dev libcodec2-dev codec2
      - name: setup cmake
        run: |
          cd ${{github.workspace}}
          cmake -B build -DOPENRTX_TARGET=linux
          cmake --build build
      - name: Run all unit tests
        run: ctest --test-dir build --output-on-failure
